spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://13.125.104.251:3306/projectWST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gimpo123
    hikari:
      maximum-pool-size: 500
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 20
      idle-timeout: 600000
      max-lifetime: 1800000
  mybatis:
    mapper-locations: mappers/**/*.xml
    configuration:
      map-underscore-to-camel-case: true